### PR TITLE
Make an UI string translatable

### PR DESCRIPTION
**Pull request by alexclassroom**
Make the string "Exclude Disable Comments Settings Based On User Roles" can be translatable

### CODE REVIEW

**Comment by abid112** [comment]
Hy @alexclassroom , Thanks for the PR!
We will merge it in our next update. Also, we're checking and planning the localization for all our missing strings.

Cheers!

**Comment by alexclassroom** [comment]
Thanks for the quick response, Please also make the UI strings in JS files translatable.

**Comment by abid112** [comment]
Hi @alexclassroom ,

We’ve just released a new version **v2.4.1** today where we merged your PR and added the localization support for all strings along with the JS strings.

So could you please update the latest  **v2.4.1* and check now? 

Let me know how it goes.
Cheers!

**Comment by alexclassroom** [comment]
I already fully [localized zh_TW UI strings](https://translate.wordpress.org/locale/zh-tw/default/wp-plugins/disable-comments/), and this I18N issue seemed to be resolved, including JS strings.

Thanks for this update.

**Comment by abid112** [comment]
Awesome @alexclassroom !
If you love Disable Comments plugin, that would be awesome if you rate us **5**  from here: https://wordpress.org/support/plugin/disable-comments/reviews/#new-post

This will help us to grow more!
Thank you and have a good day!

**Pull request merged**
